# Generated by Django 2.2.3 on 2019-07-18 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=11)),
                ('addtime', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomerLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addtime', models.DateTimeField()),
                ('ordervalue', models.FloatField()),
                ('arrears', models.FloatField()),
                ('comment', models.CharField(max_length=256)),
                ('ocn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerOrderType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=128)),
                ('value', models.FloatField()),
                ('fn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Factory')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addtime', models.DateTimeField()),
                ('ordervalue', models.FloatField()),
                ('comment', models.CharField(max_length=256)),
                ('fn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Factory')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('r', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Role')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('fn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Factory')),
                ('pm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.ProductModel')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.PurchaseOrder')),
                ('pm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.ProductModel')),
            ],
        ),
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.CustomerOrder')),
                ('pm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.ProductModel')),
            ],
        ),
        migrations.AddField(
            model_name='customerorder',
            name='on',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.CustomerOrderType'),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='os',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.OrderStatus'),
        ),
        migrations.AddField(
            model_name='customer',
            name='cl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.CustomerLevel'),
        ),
        migrations.AddField(
            model_name='customer',
            name='ct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.CustomerType'),
        ),
    ]
