# Generated by Django 2.2.3 on 2019-07-18 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='fn',
        ),
    ]
