# Generated by Django 2.2.3 on 2019-07-18 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_remove_stock_fn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerorder',
            name='os',
        ),
        migrations.AddField(
            model_name='customerorder',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='OrderStatus',
        ),
    ]
