# Generated by Django 2.2.3 on 2019-07-18 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20190718_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.RemoveField(
            model_name='customerorder',
            name='status',
        ),
        migrations.AddField(
            model_name='customerorder',
            name='os',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.OrderStatus'),
        ),
    ]
