# Generated by Django 2.2.3 on 2019-07-18 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20190718_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='os',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.OrderStatus'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=32),
        ),
    ]
