# Generated by Django 2.2.3 on 2019-07-19 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_auto_20190719_0850'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderList',
        ),
    ]
