# Generated by Django 2.2.3 on 2019-07-19 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_delete_orderlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerorder',
            name='id',
        ),
        migrations.AddField(
            model_name='customerorder',
            name='ordernum',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
