# Generated by Django 2.2.3 on 2019-07-19 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_auto_20190719_0853'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key='ordernum', serialize=False, to='crm.CustomerOrder')),
                ('pm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.ProductModel')),
            ],
        ),
    ]
