# Generated by Django 2.2.3 on 2019-07-19 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_orderlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='ctime',
            field=models.DateTimeField(default='2019-07-19 09:13:07'),
        ),
        migrations.AddField(
            model_name='orderlist',
            name='productnum',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='ordernum',
            field=models.BigIntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
