# Generated by Django 2.2.3 on 2019-07-19 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_auto_20190719_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='addtime',
            field=models.DateTimeField(default='2019-07-19 09:21:01'),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='ctime',
            field=models.DateTimeField(default='2019-07-19 09:21:01'),
        ),
    ]
