# Generated by Django 2.2.3 on 2019-07-19 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_auto_20190719_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlist',
            name='ctime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
