# Generated by Django 2.2.3 on 2019-07-19 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_auto_20190719_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='ocn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocn', to='crm.Customer'),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key='ordernum', serialize=False, to='crm.CustomerOrder'),
        ),
    ]
