# Generated by Django 2.2.3 on 2019-07-19 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_auto_20190719_1329'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderList',
        ),
    ]
